// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.11.2
// source: yolo_grpc.proto

package odam

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ObjectInformation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CamId       string           `protobuf:"bytes,1,opt,name=cam_id,json=camId,proto3" json:"cam_id,omitempty"`
	Timestamp   int64            `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Image       []byte           `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"` // bytes of full image in PNG - format
	Detection   *Detection       `protobuf:"bytes,4,opt,name=detection,proto3" json:"detection,omitempty"`
	Class       *ClassInfo       `protobuf:"bytes,5,opt,name=class,proto3" json:"class,omitempty"`
	VirtualLine *VirtualLineInfo `protobuf:"bytes,6,opt,name=virtual_line,json=virtualLine,proto3" json:"virtual_line,omitempty"`
}

func (x *ObjectInformation) Reset() {
	*x = ObjectInformation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yolo_grpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ObjectInformation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectInformation) ProtoMessage() {}

func (x *ObjectInformation) ProtoReflect() protoreflect.Message {
	mi := &file_yolo_grpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectInformation.ProtoReflect.Descriptor instead.
func (*ObjectInformation) Descriptor() ([]byte, []int) {
	return file_yolo_grpc_proto_rawDescGZIP(), []int{0}
}

func (x *ObjectInformation) GetCamId() string {
	if x != nil {
		return x.CamId
	}
	return ""
}

func (x *ObjectInformation) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ObjectInformation) GetImage() []byte {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *ObjectInformation) GetDetection() *Detection {
	if x != nil {
		return x.Detection
	}
	return nil
}

func (x *ObjectInformation) GetClass() *ClassInfo {
	if x != nil {
		return x.Class
	}
	return nil
}

func (x *ObjectInformation) GetVirtualLine() *VirtualLineInfo {
	if x != nil {
		return x.VirtualLine
	}
	return nil
}

type Detection struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	XLeft  int32 `protobuf:"varint,1,opt,name=x_left,json=xLeft,proto3" json:"x_left,omitempty"`
	YTop   int32 `protobuf:"varint,2,opt,name=y_top,json=yTop,proto3" json:"y_top,omitempty"`
	Height int32 `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	Width  int32 `protobuf:"varint,4,opt,name=width,proto3" json:"width,omitempty"`
}

func (x *Detection) Reset() {
	*x = Detection{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yolo_grpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Detection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Detection) ProtoMessage() {}

func (x *Detection) ProtoReflect() protoreflect.Message {
	mi := &file_yolo_grpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Detection.ProtoReflect.Descriptor instead.
func (*Detection) Descriptor() ([]byte, []int) {
	return file_yolo_grpc_proto_rawDescGZIP(), []int{1}
}

func (x *Detection) GetXLeft() int32 {
	if x != nil {
		return x.XLeft
	}
	return 0
}

func (x *Detection) GetYTop() int32 {
	if x != nil {
		return x.YTop
	}
	return 0
}

func (x *Detection) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Detection) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

type ClassInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClassId   int32  `protobuf:"varint,1,opt,name=class_id,json=classId,proto3" json:"class_id,omitempty"`
	ClassName string `protobuf:"bytes,2,opt,name=class_name,json=className,proto3" json:"class_name,omitempty"`
}

func (x *ClassInfo) Reset() {
	*x = ClassInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yolo_grpc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClassInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassInfo) ProtoMessage() {}

func (x *ClassInfo) ProtoReflect() protoreflect.Message {
	mi := &file_yolo_grpc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassInfo.ProtoReflect.Descriptor instead.
func (*ClassInfo) Descriptor() ([]byte, []int) {
	return file_yolo_grpc_proto_rawDescGZIP(), []int{2}
}

func (x *ClassInfo) GetClassId() int32 {
	if x != nil {
		return x.ClassId
	}
	return 0
}

func (x *ClassInfo) GetClassName() string {
	if x != nil {
		return x.ClassName
	}
	return ""
}

type VirtualLineInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	LeftX  int32 `protobuf:"varint,2,opt,name=left_x,json=leftX,proto3" json:"left_x,omitempty"`
	LeftY  int32 `protobuf:"varint,3,opt,name=left_y,json=leftY,proto3" json:"left_y,omitempty"`
	RightX int32 `protobuf:"varint,4,opt,name=right_x,json=rightX,proto3" json:"right_x,omitempty"`
	RightY int32 `protobuf:"varint,5,opt,name=right_y,json=rightY,proto3" json:"right_y,omitempty"`
}

func (x *VirtualLineInfo) Reset() {
	*x = VirtualLineInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yolo_grpc_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VirtualLineInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VirtualLineInfo) ProtoMessage() {}

func (x *VirtualLineInfo) ProtoReflect() protoreflect.Message {
	mi := &file_yolo_grpc_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VirtualLineInfo.ProtoReflect.Descriptor instead.
func (*VirtualLineInfo) Descriptor() ([]byte, []int) {
	return file_yolo_grpc_proto_rawDescGZIP(), []int{3}
}

func (x *VirtualLineInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *VirtualLineInfo) GetLeftX() int32 {
	if x != nil {
		return x.LeftX
	}
	return 0
}

func (x *VirtualLineInfo) GetLeftY() int32 {
	if x != nil {
		return x.LeftY
	}
	return 0
}

func (x *VirtualLineInfo) GetRightX() int32 {
	if x != nil {
		return x.RightX
	}
	return 0
}

func (x *VirtualLineInfo) GetRightY() int32 {
	if x != nil {
		return x.RightY
	}
	return 0
}

type Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Warning string `protobuf:"bytes,2,opt,name=warning,proto3" json:"warning,omitempty"`
	Error   string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *Response) Reset() {
	*x = Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_yolo_grpc_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_yolo_grpc_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_yolo_grpc_proto_rawDescGZIP(), []int{4}
}

func (x *Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Response) GetWarning() string {
	if x != nil {
		return x.Warning
	}
	return ""
}

func (x *Response) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_yolo_grpc_proto protoreflect.FileDescriptor

var file_yolo_grpc_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x79, 0x6f, 0x6c, 0x6f, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x04, 0x6f, 0x64, 0x61, 0x6d, 0x22, 0xee, 0x01, 0x0a, 0x11, 0x4f, 0x62, 0x6a, 0x65,
	0x63, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x15, 0x0a,
	0x06, 0x63, 0x61, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x63,
	0x61, 0x6d, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x2d, 0x0a, 0x09, 0x64, 0x65, 0x74, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6f, 0x64,
	0x61, 0x6d, 0x2e, 0x44, 0x65, 0x74, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x09, 0x64, 0x65,
	0x74, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x25, 0x0a, 0x05, 0x63, 0x6c, 0x61, 0x73, 0x73,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6f, 0x64, 0x61, 0x6d, 0x2e, 0x43, 0x6c,
	0x61, 0x73, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x63, 0x6c, 0x61, 0x73, 0x73, 0x12, 0x38,
	0x0a, 0x0c, 0x76, 0x69, 0x72, 0x74, 0x75, 0x61, 0x6c, 0x5f, 0x6c, 0x69, 0x6e, 0x65, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6f, 0x64, 0x61, 0x6d, 0x2e, 0x56, 0x69, 0x72, 0x74,
	0x75, 0x61, 0x6c, 0x4c, 0x69, 0x6e, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0b, 0x76, 0x69, 0x72,
	0x74, 0x75, 0x61, 0x6c, 0x4c, 0x69, 0x6e, 0x65, 0x22, 0x65, 0x0a, 0x09, 0x44, 0x65, 0x74, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x15, 0x0a, 0x06, 0x78, 0x5f, 0x6c, 0x65, 0x66, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x78, 0x4c, 0x65, 0x66, 0x74, 0x12, 0x13, 0x0a, 0x05,
	0x79, 0x5f, 0x74, 0x6f, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x79, 0x54, 0x6f,
	0x70, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x77, 0x69, 0x64,
	0x74, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x22,
	0x45, 0x0a, 0x09, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x19, 0x0a, 0x08,
	0x63, 0x6c, 0x61, 0x73, 0x73, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07,
	0x63, 0x6c, 0x61, 0x73, 0x73, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x6c, 0x61, 0x73, 0x73,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x6c, 0x61,
	0x73, 0x73, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x81, 0x01, 0x0a, 0x0f, 0x56, 0x69, 0x72, 0x74, 0x75,
	0x61, 0x6c, 0x4c, 0x69, 0x6e, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x15, 0x0a, 0x06, 0x6c, 0x65,
	0x66, 0x74, 0x5f, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x65, 0x66, 0x74,
	0x58, 0x12, 0x15, 0x0a, 0x06, 0x6c, 0x65, 0x66, 0x74, 0x5f, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x6c, 0x65, 0x66, 0x74, 0x59, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x69, 0x67, 0x68,
	0x74, 0x5f, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x69, 0x67, 0x68, 0x74,
	0x58, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x69, 0x67, 0x68, 0x74, 0x5f, 0x79, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x72, 0x69, 0x67, 0x68, 0x74, 0x59, 0x22, 0x54, 0x0a, 0x08, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x77, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x77, 0x61, 0x72, 0x6e, 0x69, 0x6e, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x32, 0x49, 0x0a, 0x0b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x59, 0x4f, 0x4c, 0x4f, 0x12,
	0x3a, 0x0a, 0x0d, 0x53, 0x65, 0x6e, 0x64, 0x44, 0x65, 0x74, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x17, 0x2e, 0x6f, 0x64, 0x61, 0x6d, 0x2e, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x49, 0x6e,
	0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x0e, 0x2e, 0x6f, 0x64, 0x61, 0x6d,
	0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x08, 0x5a, 0x06, 0x2e,
	0x3b, 0x6f, 0x64, 0x61, 0x6d, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_yolo_grpc_proto_rawDescOnce sync.Once
	file_yolo_grpc_proto_rawDescData = file_yolo_grpc_proto_rawDesc
)

func file_yolo_grpc_proto_rawDescGZIP() []byte {
	file_yolo_grpc_proto_rawDescOnce.Do(func() {
		file_yolo_grpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_yolo_grpc_proto_rawDescData)
	})
	return file_yolo_grpc_proto_rawDescData
}

var file_yolo_grpc_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_yolo_grpc_proto_goTypes = []interface{}{
	(*ObjectInformation)(nil), // 0: odam.ObjectInformation
	(*Detection)(nil),         // 1: odam.Detection
	(*ClassInfo)(nil),         // 2: odam.ClassInfo
	(*VirtualLineInfo)(nil),   // 3: odam.VirtualLineInfo
	(*Response)(nil),          // 4: odam.Response
}
var file_yolo_grpc_proto_depIdxs = []int32{
	1, // 0: odam.ObjectInformation.detection:type_name -> odam.Detection
	2, // 1: odam.ObjectInformation.class:type_name -> odam.ClassInfo
	3, // 2: odam.ObjectInformation.virtual_line:type_name -> odam.VirtualLineInfo
	0, // 3: odam.ServiceYOLO.SendDetection:input_type -> odam.ObjectInformation
	4, // 4: odam.ServiceYOLO.SendDetection:output_type -> odam.Response
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_yolo_grpc_proto_init() }
func file_yolo_grpc_proto_init() {
	if File_yolo_grpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_yolo_grpc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ObjectInformation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_yolo_grpc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Detection); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_yolo_grpc_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClassInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_yolo_grpc_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VirtualLineInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_yolo_grpc_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_yolo_grpc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_yolo_grpc_proto_goTypes,
		DependencyIndexes: file_yolo_grpc_proto_depIdxs,
		MessageInfos:      file_yolo_grpc_proto_msgTypes,
	}.Build()
	File_yolo_grpc_proto = out.File
	file_yolo_grpc_proto_rawDesc = nil
	file_yolo_grpc_proto_goTypes = nil
	file_yolo_grpc_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ServiceYOLOClient is the client API for ServiceYOLO service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ServiceYOLOClient interface {
	SendDetection(ctx context.Context, in *ObjectInformation, opts ...grpc.CallOption) (*Response, error)
}

type serviceYOLOClient struct {
	cc grpc.ClientConnInterface
}

func NewServiceYOLOClient(cc grpc.ClientConnInterface) ServiceYOLOClient {
	return &serviceYOLOClient{cc}
}

func (c *serviceYOLOClient) SendDetection(ctx context.Context, in *ObjectInformation, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/odam.ServiceYOLO/SendDetection", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceYOLOServer is the server API for ServiceYOLO service.
type ServiceYOLOServer interface {
	SendDetection(context.Context, *ObjectInformation) (*Response, error)
}

// UnimplementedServiceYOLOServer can be embedded to have forward compatible implementations.
type UnimplementedServiceYOLOServer struct {
}

func (*UnimplementedServiceYOLOServer) SendDetection(context.Context, *ObjectInformation) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendDetection not implemented")
}

func RegisterServiceYOLOServer(s *grpc.Server, srv ServiceYOLOServer) {
	s.RegisterService(&_ServiceYOLO_serviceDesc, srv)
}

func _ServiceYOLO_SendDetection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ObjectInformation)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceYOLOServer).SendDetection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/odam.ServiceYOLO/SendDetection",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceYOLOServer).SendDetection(ctx, req.(*ObjectInformation))
	}
	return interceptor(ctx, in, info, handler)
}

var _ServiceYOLO_serviceDesc = grpc.ServiceDesc{
	ServiceName: "odam.ServiceYOLO",
	HandlerType: (*ServiceYOLOServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendDetection",
			Handler:    _ServiceYOLO_SendDetection_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "yolo_grpc.proto",
}
