// Code generated by protoc-gen-go. DO NOT EDIT.
// source: yolo_grpc.proto

package odam

import (
	context "context"
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CamInfo struct {
	CamId                string           `protobuf:"bytes,1,opt,name=cam_id,json=camId,proto3" json:"cam_id,omitempty"`
	Timestamp            int64            `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Image                []byte           `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	Detection            *Detection       `protobuf:"bytes,4,opt,name=detection,proto3" json:"detection,omitempty"`
	VirtualLine          *VirtualLineInfo `protobuf:"bytes,5,opt,name=virtual_line,json=virtualLine,proto3" json:"virtual_line,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *CamInfo) Reset()         { *m = CamInfo{} }
func (m *CamInfo) String() string { return proto.CompactTextString(m) }
func (*CamInfo) ProtoMessage()    {}
func (*CamInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_ffa770372640e731, []int{0}
}

func (m *CamInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CamInfo.Unmarshal(m, b)
}
func (m *CamInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CamInfo.Marshal(b, m, deterministic)
}
func (m *CamInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CamInfo.Merge(m, src)
}
func (m *CamInfo) XXX_Size() int {
	return xxx_messageInfo_CamInfo.Size(m)
}
func (m *CamInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_CamInfo.DiscardUnknown(m)
}

var xxx_messageInfo_CamInfo proto.InternalMessageInfo

func (m *CamInfo) GetCamId() string {
	if m != nil {
		return m.CamId
	}
	return ""
}

func (m *CamInfo) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *CamInfo) GetImage() []byte {
	if m != nil {
		return m.Image
	}
	return nil
}

func (m *CamInfo) GetDetection() *Detection {
	if m != nil {
		return m.Detection
	}
	return nil
}

func (m *CamInfo) GetVirtualLine() *VirtualLineInfo {
	if m != nil {
		return m.VirtualLine
	}
	return nil
}

type Detection struct {
	XLeft                int32    `protobuf:"varint,1,opt,name=x_left,json=xLeft,proto3" json:"x_left,omitempty"`
	YTop                 int32    `protobuf:"varint,2,opt,name=y_top,json=yTop,proto3" json:"y_top,omitempty"`
	Height               int32    `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	Width                int32    `protobuf:"varint,4,opt,name=width,proto3" json:"width,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Detection) Reset()         { *m = Detection{} }
func (m *Detection) String() string { return proto.CompactTextString(m) }
func (*Detection) ProtoMessage()    {}
func (*Detection) Descriptor() ([]byte, []int) {
	return fileDescriptor_ffa770372640e731, []int{1}
}

func (m *Detection) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Detection.Unmarshal(m, b)
}
func (m *Detection) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Detection.Marshal(b, m, deterministic)
}
func (m *Detection) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Detection.Merge(m, src)
}
func (m *Detection) XXX_Size() int {
	return xxx_messageInfo_Detection.Size(m)
}
func (m *Detection) XXX_DiscardUnknown() {
	xxx_messageInfo_Detection.DiscardUnknown(m)
}

var xxx_messageInfo_Detection proto.InternalMessageInfo

func (m *Detection) GetXLeft() int32 {
	if m != nil {
		return m.XLeft
	}
	return 0
}

func (m *Detection) GetYTop() int32 {
	if m != nil {
		return m.YTop
	}
	return 0
}

func (m *Detection) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *Detection) GetWidth() int32 {
	if m != nil {
		return m.Width
	}
	return 0
}

type VirtualLineInfo struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	LeftX                int32    `protobuf:"varint,2,opt,name=left_x,json=leftX,proto3" json:"left_x,omitempty"`
	LeftY                int32    `protobuf:"varint,3,opt,name=left_y,json=leftY,proto3" json:"left_y,omitempty"`
	RightX               int32    `protobuf:"varint,4,opt,name=right_x,json=rightX,proto3" json:"right_x,omitempty"`
	RightY               int32    `protobuf:"varint,5,opt,name=right_y,json=rightY,proto3" json:"right_y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VirtualLineInfo) Reset()         { *m = VirtualLineInfo{} }
func (m *VirtualLineInfo) String() string { return proto.CompactTextString(m) }
func (*VirtualLineInfo) ProtoMessage()    {}
func (*VirtualLineInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_ffa770372640e731, []int{2}
}

func (m *VirtualLineInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VirtualLineInfo.Unmarshal(m, b)
}
func (m *VirtualLineInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VirtualLineInfo.Marshal(b, m, deterministic)
}
func (m *VirtualLineInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VirtualLineInfo.Merge(m, src)
}
func (m *VirtualLineInfo) XXX_Size() int {
	return xxx_messageInfo_VirtualLineInfo.Size(m)
}
func (m *VirtualLineInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_VirtualLineInfo.DiscardUnknown(m)
}

var xxx_messageInfo_VirtualLineInfo proto.InternalMessageInfo

func (m *VirtualLineInfo) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *VirtualLineInfo) GetLeftX() int32 {
	if m != nil {
		return m.LeftX
	}
	return 0
}

func (m *VirtualLineInfo) GetLeftY() int32 {
	if m != nil {
		return m.LeftY
	}
	return 0
}

func (m *VirtualLineInfo) GetRightX() int32 {
	if m != nil {
		return m.RightX
	}
	return 0
}

func (m *VirtualLineInfo) GetRightY() int32 {
	if m != nil {
		return m.RightY
	}
	return 0
}

type Response struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Warning              string   `protobuf:"bytes,2,opt,name=warning,proto3" json:"warning,omitempty"`
	Error                string   `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_ffa770372640e731, []int{3}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Response) GetWarning() string {
	if m != nil {
		return m.Warning
	}
	return ""
}

func (m *Response) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*CamInfo)(nil), "license_plate_recognition.CamInfo")
	proto.RegisterType((*Detection)(nil), "license_plate_recognition.Detection")
	proto.RegisterType((*VirtualLineInfo)(nil), "license_plate_recognition.VirtualLineInfo")
	proto.RegisterType((*Response)(nil), "license_plate_recognition.Response")
}

func init() { proto.RegisterFile("yolo_grpc.proto", fileDescriptor_ffa770372640e731) }

var fileDescriptor_ffa770372640e731 = []byte{
	// 401 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x52, 0x4d, 0x8f, 0xd3, 0x30,
	0x10, 0x25, 0xdd, 0x75, 0x4a, 0x66, 0x17, 0x56, 0x32, 0x5f, 0x01, 0x71, 0x88, 0x02, 0x87, 0x88,
	0x43, 0x0f, 0xcb, 0x3f, 0x00, 0x2e, 0x2b, 0x2d, 0x17, 0x6f, 0x85, 0x5a, 0x2e, 0x96, 0x49, 0xa6,
	0xa9, 0xa5, 0xc4, 0x8e, 0x1c, 0xd3, 0x26, 0x47, 0x7e, 0x2d, 0x7f, 0x03, 0xd9, 0x49, 0x1a, 0x09,
	0x69, 0x7b, 0x7c, 0x6f, 0xc6, 0x7e, 0xef, 0xcd, 0x0c, 0xdc, 0xf4, 0xba, 0xd2, 0xbc, 0x34, 0x4d,
	0xbe, 0x6a, 0x8c, 0xb6, 0x9a, 0xbe, 0xad, 0x64, 0x8e, 0xaa, 0x45, 0xde, 0x54, 0xc2, 0x22, 0x37,
	0x98, 0xeb, 0x52, 0x49, 0x2b, 0xb5, 0x4a, 0xff, 0x06, 0xb0, 0xfc, 0x2a, 0xea, 0x3b, 0xb5, 0xd3,
	0xf4, 0x15, 0x84, 0xb9, 0xa8, 0xb9, 0x2c, 0xe2, 0x20, 0x09, 0xb2, 0x88, 0x91, 0x5c, 0xd4, 0x77,
	0x05, 0x7d, 0x0f, 0x91, 0x95, 0x35, 0xb6, 0x56, 0xd4, 0x4d, 0xbc, 0x48, 0x82, 0xec, 0x82, 0xcd,
	0x04, 0x7d, 0x09, 0x44, 0xd6, 0xa2, 0xc4, 0xf8, 0x22, 0x09, 0xb2, 0x6b, 0x36, 0x00, 0xfa, 0x05,
	0xa2, 0x02, 0x2d, 0xe6, 0x4e, 0x23, 0xbe, 0x4c, 0x82, 0xec, 0xea, 0xf6, 0xe3, 0xea, 0x51, 0x17,
	0xab, 0x6f, 0x53, 0x2f, 0x9b, 0x9f, 0xd1, 0xef, 0x70, 0x7d, 0x90, 0xc6, 0xfe, 0x16, 0x15, 0xaf,
	0xa4, 0xc2, 0x98, 0xf8, 0x6f, 0x3e, 0x9d, 0xf9, 0xe6, 0xc7, 0xd0, 0x7e, 0x2f, 0x15, 0xba, 0x40,
	0xec, 0xea, 0x30, 0x13, 0x29, 0x42, 0x74, 0x92, 0x71, 0x51, 0x3b, 0x5e, 0xe1, 0xce, 0xfa, 0xa8,
	0x84, 0x91, 0xee, 0x1e, 0x77, 0x96, 0xbe, 0x00, 0xd2, 0x73, 0xab, 0x87, 0x98, 0x84, 0x5d, 0xf6,
	0x6b, 0xdd, 0xd0, 0xd7, 0x10, 0xee, 0x51, 0x96, 0x7b, 0xeb, 0x23, 0x12, 0x36, 0x22, 0x97, 0xfc,
	0x28, 0x0b, 0xbb, 0xf7, 0xf9, 0x08, 0x1b, 0x40, 0xfa, 0x27, 0x80, 0x9b, 0xff, 0x7c, 0xd0, 0xe7,
	0xb0, 0x18, 0x87, 0x4a, 0xd8, 0x42, 0x16, 0x4e, 0xdd, 0x69, 0xf3, 0x6e, 0xd4, 0x21, 0x0e, 0x6d,
	0x4e, 0x74, 0x3f, 0x0a, 0x79, 0x7a, 0x4b, 0xdf, 0xc0, 0xd2, 0x38, 0x41, 0xde, 0x8d, 0x4a, 0xa1,
	0x87, 0x9b, 0xb9, 0xd0, 0xfb, 0xd9, 0x4c, 0x85, 0x6d, 0xba, 0x86, 0xa7, 0x0c, 0xdb, 0x46, 0xab,
	0x16, 0x69, 0x0c, 0xcb, 0x1a, 0xdb, 0xd6, 0x6d, 0x68, 0xd8, 0xea, 0x04, 0x5d, 0xe5, 0x28, 0x8c,
	0x92, 0xaa, 0xf4, 0x36, 0x22, 0x36, 0x41, 0x97, 0x0c, 0x8d, 0xd1, 0xc6, 0xfb, 0x88, 0xd8, 0x00,
	0x6e, 0x0b, 0x08, 0x1f, 0xd6, 0x5b, 0x5d, 0x69, 0xfa, 0x13, 0x9e, 0x3d, 0xa0, 0x2a, 0xe6, 0x71,
	0xa6, 0x67, 0x96, 0x32, 0x5e, 0xd7, 0xbb, 0x0f, 0x67, 0x7a, 0x26, 0xb7, 0xe9, 0x93, 0x5f, 0xa1,
	0x3f, 0xd9, 0xcf, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0x9f, 0xea, 0x20, 0x37, 0xc5, 0x02, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// STYoloClient is the client API for STYolo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type STYoloClient interface {
	SendDetection(ctx context.Context, in *CamInfo, opts ...grpc.CallOption) (*Response, error)
}

type sTYoloClient struct {
	cc grpc.ClientConnInterface
}

func NewSTYoloClient(cc grpc.ClientConnInterface) STYoloClient {
	return &sTYoloClient{cc}
}

func (c *sTYoloClient) SendDetection(ctx context.Context, in *CamInfo, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/license_plate_recognition.STYolo/SendDetection", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// STYoloServer is the server API for STYolo service.
type STYoloServer interface {
	SendDetection(context.Context, *CamInfo) (*Response, error)
}

// UnimplementedSTYoloServer can be embedded to have forward compatible implementations.
type UnimplementedSTYoloServer struct {
}

func (*UnimplementedSTYoloServer) SendDetection(ctx context.Context, req *CamInfo) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendDetection not implemented")
}

func RegisterSTYoloServer(s *grpc.Server, srv STYoloServer) {
	s.RegisterService(&_STYolo_serviceDesc, srv)
}

func _STYolo_SendDetection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CamInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(STYoloServer).SendDetection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/license_plate_recognition.STYolo/SendDetection",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(STYoloServer).SendDetection(ctx, req.(*CamInfo))
	}
	return interceptor(ctx, in, info, handler)
}

var _STYolo_serviceDesc = grpc.ServiceDesc{
	ServiceName: "license_plate_recognition.STYolo",
	HandlerType: (*STYoloServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendDetection",
			Handler:    _STYolo_SendDetection_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "yolo_grpc.proto",
}
